version: '3.7'
services:

  web:
    image: nginx:1.21.4-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: php:8.0.13-fpm
    volumes:
      - .:/var/www/html