version: '3.7'
services:
  php:
    build: .
    networks:
      - backend
    volumes:
      - .:/var/www/html/
    container_name: php
    ports:
      - "8080:80"
    working_dir: /var/www/html/
    command: bash -c "php -S php:80 -t public"
    depends_on:
      - mysql

  mysql8:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    container_name: mysql8

  phpmyadmin:
    depends_on:
      - mysql8
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql8
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    networks:
      - backend

networks:
  backend:
volumes:
  data:
